[package]
name = "terrarium"
version = "0.1.0"
authors = ["cphos", "Zyansheep"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "2.33.1", features = ["yaml"]}
