name: terrarium
version: "0.1.0"
author: cphos, Zyansheep
about: A Terraria server written in Rust
args:
    - world:
        short: w
        long: world
        value_name: WORLD FILE or DIRECTORY
        takes_value: true
        help: The world to host
    - config:
        short: c
        long: config
        value_name: CONFIG FILE
        takes_value: true
        help: Run server with config.yml file that configures the server
    - port:
        short: p
        long: port
        value_name: <PORT>
        help: Port to open to host server
        takes_value: true
subcommands:
    - convert:
        about: Converts a vanilla format world to a terrarium format world
        args:
            - input:
                help: The input file.
                required: true
                short: i
                takes_value: true
                value_name: INPUT FILE
            - output:
                help: The output file.
                required: true
                short: o
                takes_value: true
                value_name: OUTPUT FILE
